SWM-M3PRO/GroundFlip-BE

- .github/workflows/cd_dev.yml
- src/main/resources/application.yml
git action에 환경변수 등록
merge한 git branch에서 새 pr날리기
> M3-108 Refactor : git action 환경변수 등록

- src/main/java/com/m3pro/groundflip/controller/StepController.java
- src/main/java/com/m3pro/groundflip/repository/StepRecordRepository.java
- src/main/java/com/m3pro/groundflip/service/StepService.java
- src/main/java/com/m3pro/groundflip/service/UserService.java
-빈 날짜의 걸음수를 0으로 채워서 값을 가져오도록
- left join, recursive with을 사용하는 것 보다 백엔드단에서 직접 넣어주는게 좋을 것 같아서 이렇게 사용하게 되었다.
- 변수, 함수명, 로
> M3-182 걸음수 가져오는 로직 수정

- .github/workflows/cd_dev.yml
- .gitignore
- build.gradle
- deploy.sh
- src/main/java/com/m3pro/groundflip/GroundFlipApplication.java
- src/main/java/com/m3pro/groundflip/config/LoggerInterceptor.java
- src/main/java/com/m3pro/groundflip/config/WebMvcConfig.java
- src/main/java/com/m3pro/groundflip/domain/dto/user/UserInfoRequest.java
- src/main/java/com/m3pro/groundflip/exception/AppExceptionHandler.java
- src/main/resources/application-dev.yml
- src/main/resources/application-local.yml
- src/main/resources/application.yml
- src/main/resources/logback-spring.xml
- 로그 남기기
- 우선 인터셉터를 사용해 request, response에 대해서만 로그를 남겼다. INFO 등급 이상의 로그만 남기게끔 했다.
- 10일간 로그를 저장하며 docker의 볼륨기능을 사용해 ec2의 logs 디렉토리에 저장함.
> M3-190 로그 남기기

- src/main/java/com/m3pro/groundflip/controller/UserController.java
- src/main/java/com/m3pro/groundflip/domain/dto/user/UserInfoResponse.java
- src/main/java/com/m3pro/groundflip/service/UserService.java
- src/main/java/com/m3pro/groundflip/util/S3Uploader.java
- 이미지가 null로 들어올때 s3에 업로드 하지 않고 테이블에 빈 값을 넣어준다
- null일때 exception이 나지 않도록 하고 예외를 처리해 주도록 하기
- 문제가 되는 부분이 없는지
> M3-193 이미지 null 일때 처리

- .github/workflows/cd_dev.yml
- src/test/java/com/m3pro/groundflip/service/UserServiceTest.java
> M3-197 aws 환경변수 수정

- src/main/java/com/m3pro/groundflip/service/AuthService.java
- src/main/java/com/m3pro/groundflip/service/PixelEventListener.java
- src/main/java/com/m3pro/groundflip/service/PixelService.java
- src/main/java/com/m3pro/groundflip/service/oauth/KakaoApiClient.java
- src/main/java/com/m3pro/groundflip/service/oauth/OauthService.java
> M3-199 주석 - 민욱

- src/main/java/com/m3pro/groundflip/jwt/JwtProvider.java
- src/main/java/com/m3pro/groundflip/service/AuthService.java
- src/main/java/com/m3pro/groundflip/service/PixelService.java
- src/main/java/com/m3pro/groundflip/service/RankingService.java
- src/main/java/com/m3pro/groundflip/service/ReverseGeoCodingService.java
- src/main/java/com/m3pro/groundflip/service/UserService.java
- src/main/java/com/m3pro/groundflip/service/oauth/AppleApiClient.java
- src/main/java/com/m3pro/groundflip/service/oauth/ApplePublicKeyGenerator.java
- src/test/java/com/m3pro/groundflip/jwt/JwtProviderTest.java
- 공통 주석 달기
- appleOauthClient 리팩토링
> M3-198 주석 - 구민

- src/main/java/com/m3pro/groundflip/controller/StepController.java
- src/main/java/com/m3pro/groundflip/domain/dto/steprecord/UserStepInfo.java
- src/main/java/com/m3pro/groundflip/service/CommunityService.java
- src/main/java/com/m3pro/groundflip/service/StepService.java
- src/main/java/com/m3pro/groundflip/service/UserService.java
- service단 주석 작성
- 이미지가 null로 들어오면 테이블의 이미지가 사라지는 문제 해결
- 주석 형태
> M3-200 주석-상민

- .github/workflows/cd_dev.yml
- 완료한 사항1
- 완료한 사항2
- 무슨 이유로 어떻게 코드를 변경했는지
- 기술적 고민
> M3-230 애플 계정 탈퇴 기능 구현 (cd 환경변수 추가)

- .github/workflows/cd_prod.yml
- src/main/resources/application-prod.yml
> M3-219 운영용 CICD 구축

- build.gradle
- src/main/java/com/m3pro/groundflip/repository/PixelRepository.java
- src/main/java/com/m3pro/groundflip/service/PixelService.java
- src/main/java/com/m3pro/groundflip/util/DateUtils.java
- src/test/java/com/m3pro/groundflip/repository/PixelRepositoryTest.java
- src/test/java/com/m3pro/groundflip/util/DateUtilsTest.java
- 이번주의 소유된 픽셀만 반환하도록 수정
- modified_at 필드를 사용하여 이번주에 소유된 픽셀인지 확인하도록 했다.
> M3 224 일주일에 한번 픽셀 소유 초기화

- src/main/java/com/m3pro/groundflip/controller/PixelController.java
- src/main/java/com/m3pro/groundflip/repository/PixelRepository.java
- src/main/java/com/m3pro/groundflip/repository/PixelUserRepository.java
- src/main/java/com/m3pro/groundflip/service/PixelService.java
- src/test/java/com/m3pro/groundflip/service/PixelServiceTest.java
- 픽셀 정보를 필터링 할 수 있게 api 수정
- 픽셀 개수를 필터링 할 수 있게 api 수정
- 날짜를 선택하면 해당날짜이후에 날짜를 필터링 하도록 수정 했다.
> M3-246 픽셀 정보를 필터링 할 수 있게 api 수정

- src/main/java/com/m3pro/groundflip/service/UserService.java
- src/main/java/com/m3pro/groundflip/util/S3Uploader.java
- src/main/resources/application-local.yml
- src/test/java/com/m3pro/groundflip/service/UserServiceTest.java
- s3에 파일을 업로드 시 '###' + userId
- 이미지 압축시 소요시간
- 이미지 압축 로직
> M3-235 s3 이미지 압축

- src/main/java/com/m3pro/groundflip/service/MyPlaceService.java
- src/test/java/com/m3pro/groundflip/service/MyPlaceServiceTest.java
- 즐겨찾기가 null일시 빈 리스트를 반환
- 기존 exception을 삭제
> M3-212: 즐겨찾기 없을시 빈 리스트 get

- src/main/java/com/m3pro/groundflip/repository/RankingRedisRepository.java
- src/main/java/com/m3pro/groundflip/service/UserService.java
- src/test/java/com/m3pro/groundflip/repository/RankingRedisRepositoryTest.java
> M3-288 유저 탈퇴시 레디스 삭제 안되는 문제

- .github/workflows/cd_dev.yml
- .github/workflows/cd_prod.yml
- src/main/java/com/m3pro/groundflip/service/AuthService.java
- src/main/java/com/m3pro/groundflip/service/VersionService.java
- src/main/resources/application-dev.yml
- src/main/resources/application-local.yml
- src/main/resources/application-prod.yml
- src/test/java/com/m3pro/groundflip/service/VersionServiceTest.java
- src/test/resources/application-test.yml
- RECOMMAND_UPDATE 환경변수 추가
- RECOMMAND_UPDATE보다 큰 버전은 업데이트가 필수가 아니다
- 이것보다 작으면 업데이트가 필수이다
- 1.0.1 , 1.0.3 이 문자열을 비교하기 위해 문자열 SPLIT
- 함수, 변수, 로직
> M3-318 버전 비교 로직 추가

- src/main/java/com/m3pro/groundflip/domain/dto/user/FcmTokenRequest.java
- src/main/java/com/m3pro/groundflip/domain/entity/FcmToken.java
- src/main/java/com/m3pro/groundflip/enums/Device.java
- src/main/java/com/m3pro/groundflip/service/FcmService.java
- src/test/java/com/m3pro/groundflip/service/FcmServiceTest.java
- FCM 토큰 안드, iOS 구분
- 토큰을 저장할 때 기기의 종류를 저장한다.
> M3-299 FCM 토큰 안드, iOS 구분

- src/main/java/com/m3pro/groundflip/controller/CommunityController.java
- src/main/java/com/m3pro/groundflip/controller/VersionController.java
- src/main/java/com/m3pro/groundflip/domain/dto/community/CommunitySearchResponse.java
- 그룹 검색시 이름, 이미지, 색을 반환하도록 수정
- 에러 수정
- 변수, 함수, 로직
> M3-355 그룹 검색 반환값 수정, 오류 수정

- src/main/java/com/m3pro/groundflip/domain/dto/community/CommunitySearchResponse.java
- 그룹 검색 시 community id도 반환하도록 추가했다
> M3-355 Feat : 그룹 id 반환 수정

- src/main/java/com/m3pro/groundflip/controller/CommunityController.java
- src/main/java/com/m3pro/groundflip/domain/dto/community/CommunitySignRequest.java
- src/main/java/com/m3pro/groundflip/domain/entity/UserCommunity.java
- src/main/java/com/m3pro/groundflip/exception/ErrorCode.java
- src/main/java/com/m3pro/groundflip/repository/UserCommunityRepository.java
- src/main/java/com/m3pro/groundflip/service/CommunityService.java
- src/test/java/com/m3pro/groundflip/service/CommunityServiceTest.java
- 그룹 탈퇴 api 구현
- soft delete를 위해 deleted at에 nowdate를 update시켜준다
- deleted at이 null인 값을 검색해서 update한다
- 변수, 함수, 로직
> M3-342 그룹 탈퇴 API 구현

- src/main/java/com/m3pro/groundflip/controller/PixelController.java
- src/main/java/com/m3pro/groundflip/domain/dto/pixel/CommunityModePixelResponse.java
- src/main/java/com/m3pro/groundflip/repository/PixelRepository.java
- src/main/java/com/m3pro/groundflip/service/PixelReader.java
- 그룹전 픽셀 정보 반환 api 구현
- 그룹전 픽셀 개수 반환 api 구현
개인전 로직과 거의 비슷하여 개인전 기반으로 구현하였다.
> M3-348 그룹전 픽셀 정보 반환 api 구현

- src/main/java/com/m3pro/groundflip/repository/PixelUserRepository.java
- 완료한 사항1
- 완료한 사항2
- 무슨 이유로 어떻게 코드를 변경했는지
- 기술적 고민
> V1.1.0 다시 다시

- src/main/java/com/m3pro/groundflip/repository/RankingRedisRepository.java
- 완료한 사항1
- 완료한 사항2
- 무슨 이유로 어떻게 코드를 변경했는지
- 기술적 고민
> hot fix 랭킹 숫자 98 로 수정

- src/main/java/com/m3pro/groundflip/domain/dto/auth/LoginRequest.java
- src/main/java/com/m3pro/groundflip/exception/ErrorCode.java
- src/main/java/com/m3pro/groundflip/service/AuthService.java
- 이메일이 null이면 400과 error log를 반환합니다.
- 이메일이 null인 유저가 생기는 이슈가 발생했으므로
> M3-276 이메일 null일때 400 반환

- src/main/java/com/m3pro/groundflip/service/PixelManager.java
- 픽셀 점령 시 로그 추가, 리버스 지오코딩이 되지 않아도 점령되게 수정
> Hot Fix : 픽셀 점령 시 로그 추가, 리버스 지오코딩이 되지 않아도 점령되게 수정
