SWM-M3PRO/GroundFlip-BE

.github/workflows/cd_dev.yml
.github/workflows/ci.yml
.gitignore
Dockerfile
appspec.yml
deploy.sh
src/test/java/com/m3pro/groundflip/GroundFlipApplicationTests.java

- ci 구축
- 개발용 서버 cd 구축
- 도커 파일 구성
develop 브랜치에 PR을 날리면 머지하기전에 몇가지 검사를 실행하도록 했다.
- 빌드
- gradle 을 사용해 빌드 한다.
- 테스트
- gradle 을 사용해 테스트 한다.
develop 브랜치에 머지되면 자동으로 개발용 서버에 배포되게 한다. codeDeploy를 사용했다. 다만 개발용이다보니 무중단 배포는 아니고 도커 컨테이너를 내린후 새로운 컨테이너로 대체 하는 방식을 사용했다.
만약 환경변수를 건드렸다면 cd 스크립트와 레포지토리 시크릿을 바꿔야한다.
- 빌드
- 압축
- s3 업로드
- cdoe deploy 실행
- s3 에서 빌드 파일 다운
- 실행

M3-127 백엔드 도커 CI/CD 구축

---

src/main/java/com/m3pro/groundflip/config/GeometryConfig.java
src/main/java/com/m3pro/groundflip/config/GeometryConverter.java
src/main/java/com/m3pro/groundflip/controller/PixelController.java
src/main/java/com/m3pro/groundflip/domain/dto/pixel/IndividualPixelResponse.java
src/main/java/com/m3pro/groundflip/repository/PixelRepository.java
src/main/java/com/m3pro/groundflip/service/PixelService.java

- 픽셀 개인전 정보를 가져오는 API 구현
- @Query 사용
- GIS 자료형을 스프링에서 쓰기 위해 여러 제약들이 존재했음
- 스프링의 GIS 자료형은 두 가지가 있음. Geom, locationtech.
- 대부분 레퍼런스들이 locationtech를 사용했기에 그렇게 구현함.
- 하지만 Hibernate 내부에서 Geom을 사용하기에 쿼리 결과로 온 자료형이 locationtech와 호환이 안맞는 문제가 발생
- 또한 native query를 사용할 때 interface로 결과를 받아야 했지만 Point 자료형은 직렬화 ,역직렬화도 어려웠음.
- 따라서 Geom 자료형을 locationtech로 직접 변환 후 위경도값을 꺼내 DTO를 만드는 식으로 구현하였음.

M3-140 픽셀 개인전 정보를 가져오는 API 다시 만들기

---

src/main/java/com/m3pro/groundflip/domain/dto/pixel/PixelOccupyRequest.java
src/main/java/com/m3pro/groundflip/repository/PixelRepository.java
src/main/java/com/m3pro/groundflip/service/PixelService.java

- 기존에 pixelId를 받는 방식에서 상대좌표인 x,y 를 받게끔 수정
- 프론트 측에서 pixelId를 알아내기 어려워 추가적인 로직이 필요했습니다.
- 이를 해결하기 위해 프론트 측에서 스스로 알 수 있는 정보인 상대좌표로 픽셀을 특정하게끔 변경하였습니다.

M3-120 픽셀 차지하는 API가 x, y를 받게끔 수정

---

src/main/java/com/m3pro/groundflip/controller/PixelController.java
src/main/java/com/m3pro/groundflip/domain/dto/pixel/IndividualPixelInfoResponse.java
src/main/java/com/m3pro/groundflip/domain/dto/pixel/PixelOwnedUser.java
src/main/java/com/m3pro/groundflip/domain/dto/pixel/PixelOwnerUserResponse.java
src/main/java/com/m3pro/groundflip/domain/dto/pixel/VisitedUserInfo.java
src/main/java/com/m3pro/groundflip/domain/dto/pixelUser/PixelCount.java
src/main/java/com/m3pro/groundflip/domain/dto/pixelUser/PixelOwnerUser.java
src/main/java/com/m3pro/groundflip/domain/dto/pixelUser/VisitedUser.java
src/main/java/com/m3pro/groundflip/domain/entity/User.java
src/main/java/com/m3pro/groundflip/repository/PixelUserRepository.java
src/main/java/com/m3pro/groundflip/service/PixelService.java
src/test/java/com/m3pro/groundflip/service/PixelServiceTest.java

- /api/individual-mode/{pixelId} api 구현
- service 코드 단위 코드 작성
없는 픽셀의 경우는 PIXEL_NOT_FOUND 에러를 반환하게 처리헸다.
픽셀에 방문한 사용자가 없는 경우는 PixelOwnerUser 의 값을 null 로 처리 했다. 기존 로직에서 해당 부분을 처리하는 메서드를 따로 분리해 없는 경우와 있는 경우를 분리했다.
```
private PixelOwnerUserResponse getPixelOwnerUserInfo(Long pixelId) {
PixelOwnerUser pixelOwnerUser = pixelUserRepository.findCurrentOwnerByPixelId(pixelId);
if (pixelOwnerUser == null) {
return null;
} else {
PixelCount accumulatePixelCount = pixelUserRepository.findAccumulatePixelCountByUserId(
pixelOwnerUser.getUserId());
PixelCount currentPixelCount = pixelUserRepository.findCurrentPixelCountByUserId(
pixelOwnerUser.getUserId());
return PixelOwnerUserResponse.from(pixelOwnerUser, currentPixelCount, accumulatePixelCount);
}
}
```
없을 떄는 응답으로 가는 body에 null 이 들어가게 된다.
3 가지의 경우를 …

M3-143 개인전 픽셀 정보 api 구현

---

src/main/java/com/m3pro/groundflip/controller/PixelController.java
src/main/java/com/m3pro/groundflip/domain/dto/pixelUser/IndividualHistoryPixelInfoResponse.java
src/main/java/com/m3pro/groundflip/repository/PixelUserRepository.java
src/main/java/com/m3pro/groundflip/service/PixelService.java
src/main/resources/application.yml
src/test/java/com/m3pro/groundflip/service/PixelServiceTest.java
src/test/java/com/m3pro/groundflip/service/TestUtils.java

- 특정  픽셀에 대한 개인 기록 정보 가져오는 api 완성
- 해당 api에 대한 테스트 코드 작성
- 기존 sql문들 style 수정
- 아래 두 방식 중 뭐가 나을 지 고민이 됐다.
```sql
select pixel.address, pixel.address_number, pixel_user.created_at
from pixel_user
join pixel on {픽셀 아이디} = pixel.pixel_id
where user_id = {사용자 아이디};
```
```sql
select  pixel_user.created_at
from pixel_user
where pixel_user.pixel_id = {픽셀 아이디} and pixel_user.user_id = {사용자 아이디}
select *
from pixel
where pixel.pixel_id = {픽셀 아이디}
```
- 하지만 join연산은 매우 비용이 크다는 것을 고려해 단일 쿼리 두 번을 사용하고 각 쿼리가 인덱스를 타게끔 했다.
- 테스트 코드 또한 논리적으로 맞는 것인지 헷갈렸다
- 또한 테스트 코드에서 basetime entity의 createdAt을 builder로 생성할 수 없었다.
- 따라서 리플렉션 기능을 활용하여 해당 필드를 삽입하여 활용했다.
- 테스트 코드의 합당성
- 쿼리문 검토

M3-144 개인 기록 픽셀 정보 api 구현

---

src/main/java/com/m3pro/groundflip/controller/PixelController.java
src/main/java/com/m3pro/groundflip/domain/dto/pixel/PixelCountResponse.java
src/main/java/com/m3pro/groundflip/repository/PixelUserRepository.java
src/main/java/com/m3pro/groundflip/service/PixelService.java
src/test/java/com/m3pro/groundflip/service/PixelServiceTest.java

- 현재 픽셀 수, 누적 픽셀 수를 가져오는 기능 구현
- 이전에 작성된 쿼리를 개선하였다.
- 처음엔 CTE를 쓰는 등 여러 안을 생각했지만, '각 픽셀의 최신 기록을 모두 구하고 이 최신기록의 user가 누군지 확인하자'
- 라는 아이디어에 기반해 쿼리를 작성하니 매우 간결해졌다.
- 특히 별다른 조건이 없는 외래키(pixel_id)에 기반한 group by는 생각보다 빠르게 연산이 가능했다.
- 쿼리문의 합당성

M3-155 누적 픽셀, 현재 픽셀 갯수 가져오는 api 구현

---

src/main/java/com/m3pro/groundflip/config/SecurityConfig.java
src/main/java/com/m3pro/groundflip/config/SwaggerConfig.java
src/main/java/com/m3pro/groundflip/controller/AuthController.java
src/main/java/com/m3pro/groundflip/controller/CommunityController.java
src/main/java/com/m3pro/groundflip/controller/PixelController.java
src/main/java/com/m3pro/groundflip/controller/UserController.java
src/main/java/com/m3pro/groundflip/domain/dto/StepRecord/UserStepInfo.java
src/main/java/com/m3pro/groundflip/domain/dto/auth/KaKaoUserInfoResponse.java
src/main/java/com/m3pro/groundflip/domain/dto/auth/KakaoTokenValidationResponse.java
src/main/java/com/m3pro/groundflip/domain/dto/auth/LoginRequest.java
src/main/java/com/m3pro/groundflip/domain/dto/auth/LoginResponse.java
src/main/java/com/m3pro/groundflip/domain/dto/auth/OauthUserInfoResponse.java
src/main/java/com/m3pro/groundflip/domain/dto/auth/ReissueReponse.java
src/main/java/com/m3pro/groundflip/domain/dto/auth/ReissueRequest.java
src/main/java/com/m3pro/groundflip/domain/dto/auth/Tokens.java
src/main/java/com/m3pro/groundflip/domain/dto/community/CommunityInfoResponse.java
src/main/java/com/m3pro/groundflip/domain/dto/pixel/IndividualHistoryPixelResponse.java
src/main/java/com/m3pro/groundflip/domain/dto/pixel/IndividualModePixelResponse.java
src/main/java/com/m3pro/groundflip/domain/dto/pixel/IndividualPixelInfoResponse.java
src/main/java/com/m3pro/groundflip/domain/dto/pixel/PixelCountResponse.java
src/main/java/com/m3pro/groundflip/domain/dto/pixelUser/IndividualHistoryPixelInfoResponse.java
src/main/java/com/m3pro/groundflip/domain/entity/User.java
src/main/java/com/m3pro/groundflip/enums/UserStatus.java
src/main/java/com/m3pro/groundflip/jwt/JwtAuthorizationFilter.java
src/main/java/com/m3pro/groundflip/jwt/JwtExceptionFilter.java
src/main/java/com/m3pro/groundflip/jwt/JwtProvider.java
src/main/java/com/m3pro/groundflip/repository/PixelRepository.java
src/main/java/com/m3pro/groundflip/repository/PixelUserRepository.java
src/main/java/com/m3pro/groundflip/repository/UserRepository.java
src/main/java/com/m3pro/groundflip/service/AuthService.java

- 토큰 재발급 api 구현
- user pending 상태 처리
- 스웨거에 인증 인가 설정
- refresh token 을 보내면 access token 과 refresh token 까지 전부 재 발급 하도록 수정
- 사용자는 두가지 상태가 있다.
- Pending : 최초 로그인 하여 프로바이더 id 와 이메일만 등록된 상태 -> 회원가입을 하지 않은 상태
- Complete : 로그인 하고 회원가입까지 완료한 상태
따라서 위 두 상태로 분리하고 최초 로그인시 Pending 상태로 저장 하였다. 로그인 할 때 마다 User 의 status 컬럼을 보고 Pending 상태이면 isSignUp이 true 로 반환하도록 하였다.
인증이 필요한 api 에는 자물쇠 표시를 달았다. 
인증이 필요한 컨트롤러에는 `@SecurityRequirement(name = "Authorization")` 어노테이션을 반드시 붙여준다

M3-177 토큰 리프레쉬

---

.github/workflows/cd_dev.yml
.github/workflows/ci.yml
build.gradle
src/main/java/com/m3pro/groundflip/config/RedisConfig.java
src/main/resources/application-dev.yml
src/test/resources/application-test.yml

- 엘라스틱 캐시 생성 완료
- 스프링 레디스 연결
- 레디스도 외부 레디스를 연결해야하는 부분이라 SpringBootTest 를 실행할 때 에러가 발생한다. 로컬에서는 상관없지만 GitHub action 에서는 매번 레디스를 실행시켜주어야한다.
- 따라서 ci 스크립트에 도커로 레디스를 실행하는 명령어를 삽입하여 항상 레디스가 실행되도록 했다
- 혹시 추후 사용할 일이 있을수도 있을 것 같아 redisTemplate도 넣어두었습니다.

M3-171 elastic cache 연결

---

src/main/java/com/m3pro/groundflip/controller/AuthController.java
src/main/java/com/m3pro/groundflip/domain/dto/auth/LogoutRequest.java
src/main/java/com/m3pro/groundflip/domain/entity/redis/BlacklistedToken.java
src/main/java/com/m3pro/groundflip/jwt/JwtAuthorizationFilter.java
src/main/java/com/m3pro/groundflip/jwt/JwtProvider.java
src/main/java/com/m3pro/groundflip/repository/BlackListedTokenRepository.java
src/main/java/com/m3pro/groundflip/service/AuthService.java
src/test/java/com/m3pro/groundflip/jwt/JwtProviderTest.java
src/test/java/com/m3pro/groundflip/service/AuthServiceTest.java

- 로그아웃 api 구현
- 블랙 리스트 구현
- 토큰 검증시 블랙 리스트 확인
- 테스트 코드 작성
- access token 과 refresh token 모두 동일하게 저장했다. 로그아웃 요청이 오면 블랙리스트에 두 토큰을 넣는 방식으로 구현했다.
- 잘못된 토큰이 로그아웃 요청으로 오면 저장하지 않게 했다. 어차피 필요없는 토큰에 저장공간을 낭비할 필요는 없다고 생각했다.
access token 이 재발급 될 때 마다 기존에 쓰던 refresh token은 블랙리스트에 들어간다. 하지만 리프레시 토큰은 저장기간이 2주이기 때문에 오랜시간 블랙리스트에 남아 있게 되서 용량을 많이 잡아 먹을 수 있을 것 같다는 생각이 들었다.
추후에 리프레시 토큰은 블랙리스트가 아니라 화이트리스트를 만들어서 user 한명당 하나의 리프레시 토큰을 저장 시켜두고 해당 토큰만 사용가능하게 하면 개선되지 않을까 하는 생각을 해보았다.

M3-165 로그아웃 api 및 블랙 리스트

---

src/main/java/com/m3pro/groundflip/controller/TestController.java
src/main/java/com/m3pro/groundflip/controller/UserController.java
src/main/java/com/m3pro/groundflip/domain/dto/user/UserInfoRequest.java
src/main/java/com/m3pro/groundflip/domain/entity/StepRecord.java
src/main/java/com/m3pro/groundflip/domain/entity/User.java
src/main/java/com/m3pro/groundflip/exception/ErrorCode.java
src/main/java/com/m3pro/groundflip/repository/UserRepository.java
src/main/java/com/m3pro/groundflip/service/UserService.java

- 유저 닉네임, 성별, 생년 수정
- 중복 닉네임이면 에러반환
- 완료 후 status complete
- 닉네임 중복을 확인하기 위해서 현재 닉네임과 업데이트 닉네임이 다르고, 업데이트 닉네임이 테이블에 없으면 수정하도록 했다.
- 함수, 클래스, 변수명, 로직

M3-167 유저정보 수정

---

.github/workflows/ci.yml
src/main/java/com/m3pro/groundflip/controller/PixelController.java
src/main/java/com/m3pro/groundflip/domain/dto/pixel/PixelCountResponse.java
src/main/java/com/m3pro/groundflip/domain/dto/pixel/PixelOwnerUserResponse.java
src/main/java/com/m3pro/groundflip/repository/PixelRepository.java
src/main/java/com/m3pro/groundflip/repository/PixelUserRepository.java
src/main/java/com/m3pro/groundflip/service/PixelService.java
src/main/java/com/m3pro/groundflip/service/ReverseGeoCodingService.java
src/main/java/com/m3pro/groundflip/service/oauth/KakaoApiClient.java
src/main/java/com/m3pro/groundflip/service/oauth/OauthApiClient.java
src/main/java/com/m3pro/groundflip/service/oauth/OauthService.java
src/test/java/com/m3pro/groundflip/repository/PixelRepositoryTest.java
src/test/java/com/m3pro/groundflip/service/PixelServiceTest.java
src/test/resources/application-test.yml

- getIndividualModePixelInfo 에서 역정규화된 pixel을 활용하도록 수정
- ReverseGeoCodingService 분리
- 픽셀 수를 세는 레파지토리 코드를 Jpql 로 수정
- 테스트용 redis 포트를 6378로 변경
- Jacoco 커버리지 리포트를 ci 마다 새로 생성하는 것이 아니라 기존 리포트를 수정하도록 변경
```
private PixelOwnerUserResponse getPixelOwnerUserInfo(Pixel pixel) {
Long ownerUserId = pixel.getUserId();
if (ownerUserId == null) {
return null;
} else {
PixelCount accumulatePixelCount = pixelUserRepository.findAccumulatePixelCountByUserId(ownerUserId);
PixelCount currentPixelCount = pixelRepository.findCurrentPixelCountByUserId(ownerUserId);
User ownerUser = userRepository.findById(ownerUserId)
.orElseThrow(() -> {
log.error("pixel {} 의 소유자가 {} 인데 존재하지 않음.", pixel.getId(), ownerUserId);
return new AppException(ErrorCode.INTERNAL_SERVER_ERROR);
});
return …
```

M3-157 db역정규화 - 구민분량

---

src/main/java/com/m3pro/groundflip/controller/RankingController.java
src/main/java/com/m3pro/groundflip/domain/dto/ranking/Ranking.java
src/main/java/com/m3pro/groundflip/domain/dto/ranking/UserRankingResponse.java
src/main/java/com/m3pro/groundflip/domain/entity/User.java
src/main/java/com/m3pro/groundflip/repository/RankingRedisRepository.java
src/main/java/com/m3pro/groundflip/service/PixelService.java
src/main/java/com/m3pro/groundflip/service/RankingService.java
src/test/java/com/m3pro/groundflip/repository/RankingRedisRepositoryTest.java
src/test/java/com/m3pro/groundflip/service/PixelServiceTest.java
src/test/java/com/m3pro/groundflip/service/RankingServiceTest.java

- 상위 30명 랭킹을 불러오는 api 구현
- 특정 유저의 등수를 불러오는 api 구현
처음에는 
```
public List<UserRankingResponse> getAllUserRanking() {
List<Ranking> rankings = rankingRedisRepository.getRankingsWithCurrentPixelCount();
return rankings.stream()
.map(ranking -> {
User user = userRepository.findById(ranking.getUserId())
.orElseThrow(() -> new RuntimeException("User not found"));
return UserRankingResponse.from(user, ranking.getRank(), ranking.getCurrentPixelCount());
})
.collect(Collectors.toList());
}
```
위와 같이 레디스에서 랭킹을 가져오고 랭킹을 map 함수로 변환하면서 user 정보를 하나씩 DB 에서 가져오는 방식을 사용했더니 코드는 간단했지만 api 응답속도가 약 1400ms 로 매우 느렸다. 많은 조회를 해서 오래 걸리는 것 같아 Transsaction 으로 묶었더니 300ms 까지 줄었다.
하지만 생각해보니 DB에서 user 를 가져올 때 한번에 다 가져오면 여러번 요청 보낼 필요가 없으니 더 빨라질 것이라고 생각했다. 그래서 랭킹에 속해있는 id 들을 한번 조회해서 사용하는 방식으로 바꾸었다. (현재 코드에 반영되어있는 코드)
그결과 약 …

M3-184 현재 랭킹을 반환하는 api 구현

---

.github/workflows/cd_dev.yml
src/main/java/com/m3pro/groundflip/controller/AuthController.java
src/main/java/com/m3pro/groundflip/domain/dto/auth/AppleUserInfoResponse.java
src/main/java/com/m3pro/groundflip/domain/dto/auth/apple/ApplePublicKey.java
src/main/java/com/m3pro/groundflip/domain/dto/auth/apple/ApplePublicKeyResponse.java
src/main/java/com/m3pro/groundflip/jwt/JwtProvider.java
src/main/java/com/m3pro/groundflip/service/oauth/AppleApiClient.java
src/main/java/com/m3pro/groundflip/service/oauth/ApplePublicKeyGenerator.java
src/main/resources/application-dev.yml
src/main/resources/application-local.yml
src/test/java/com/m3pro/groundflip/jwt/JwtProviderTest.java
src/test/java/com/m3pro/groundflip/service/AuthServiceTest.java
src/test/resources/application-test.yml

- 애플 로그인 api 구현
- 클라이언트는 서버에 identity token을 넘겨준다.
- identity token은 jwt 토큰이다. 이안에 이메일, 식별자 등 필요한 정보가 담겨있다. 따라서 이 토큰을 검증해서 유효한 토큰이면 로그인이나 회원가입 절차를 진행하면 된다.
-  검증하려면 애플로부터 public 키를 받아 jwt 유효성을 확인하면 된다. 이 과정이 좀 복잡해서 컨플루언스에 남기겠다.

M3-195 애플 로그인 api 구현

---

src/main/java/com/m3pro/groundflip/GroundFlipApplication.java
src/main/java/com/m3pro/groundflip/config/AsyncConfig.java
src/main/java/com/m3pro/groundflip/domain/dto/pixel/event/PixelAddressUpdateEvent.java
src/main/java/com/m3pro/groundflip/domain/dto/pixel/event/PixelUserInsertEvent.java
src/main/java/com/m3pro/groundflip/repository/PixelUserRepository.java
src/main/java/com/m3pro/groundflip/service/PixelEventListener.java
src/main/java/com/m3pro/groundflip/service/PixelService.java
src/test/java/com/m3pro/groundflip/repository/PixelUserRepositoryTest.java
src/test/java/com/m3pro/groundflip/service/PixelEventListenerTest.java
src/test/java/com/m3pro/groundflip/service/PixelServiceTest.java

- pixelUser record가 비동기적으로 실행되게끔 수정
- updatePixel address가 비동기적으로 실행되게끔 수정
- 테스트 코드 작성
성능 향상과 의존성 낮추기
- 기존의 occupyPixel()은 지나치게 많은 일을 하고 있었음.
- 심지어 이런 많은 일들이 불필요하게 하나의 transaction으로 묶여있었음
<br>
- 따라서 단순히 사용자의 history를 남기는 기능과 픽셀의 주소를 업데이트하는 기능을 Event를 활용하여 비동기로 처리함.
- 하지만 이들 각각에 대해 따로 트랜잭션을 걸어주어야 했고, @Transactional의 옵션을 사용함.
<br>
- 또한 픽셀을 업데이트 하는 함수를 분리할 때, 기존의 주소를 확인하는 과정도 event를 수신하는 측에서 처리하고 싶었으나 그렇게 되면 모든 요청마다 null check를 하기 위해 새로운 스레드가 생기는 문제가 발생하여 null check 후 이벤트를 발행하도록 구현함.
- 그리고 기존의 주소가 null이여서 event를 수신한 경우, 다른 스레드에서 작동하게 되어 영속성 컨텍스트가 비어있게 됨.
- 따라서 픽셀 주소를 update하고 메소드 끝에서 Commit이 일어날 때, select와 update 쿼리가 각각 한 번 씩 일어나게 된다.
- native query를 사용해 select문을 생략할 수 있지만 우선 위의 방식으로 구현함 (추후 논의가 필요할 듯)
<br>
- pixel table에서 user_id를 바꾸는 작업도 비동기로 바꿀 수 있었지만, 
- 1. pk 인덱스를 타는 update 쿼리가 그렇게 느리지 …

M3-189 랭킹 구현 후 pixel_user 테이블에 삽입하는 코드를 비동기로 작동하게끔 수정

---

src/main/java/com/m3pro/groundflip/controller/UserController.java
src/main/java/com/m3pro/groundflip/domain/dto/user/UserDeleteRequest.java
src/main/java/com/m3pro/groundflip/domain/entity/User.java
src/main/java/com/m3pro/groundflip/service/UserService.java
src/test/java/com/m3pro/groundflip/service/PixelServiceTest.java
src/test/java/com/m3pro/groundflip/service/UserServiceTest.java

- 회원 탈퇴 구현
- 테스트 코드 작성
- 일종의 soft delete를 구현하기 위해 유저의 정보를 null 값 등으로 masking하였다.
- 애플 회원탈퇴는 추후 구현 요망

M3-229 회원 탈퇴

---

build.gradle
src/main/java/com/m3pro/groundflip/controller/AuthController.java
src/main/java/com/m3pro/groundflip/domain/dto/auth/AppleLoginRequest.java
src/main/java/com/m3pro/groundflip/domain/dto/auth/AppleTokenResponse.java
src/main/java/com/m3pro/groundflip/domain/entity/AppleRefreshToken.java
src/main/java/com/m3pro/groundflip/repository/AppleRefreshTokenRepository.java
src/main/java/com/m3pro/groundflip/service/AuthService.java
src/main/java/com/m3pro/groundflip/service/UserService.java
src/main/java/com/m3pro/groundflip/service/oauth/AppleApiClient.java
src/main/java/com/m3pro/groundflip/service/oauth/AppleKeyGenerator.java
src/main/java/com/m3pro/groundflip/service/oauth/OauthService.java
src/main/resources/application-dev.yml
src/main/resources/application-local.yml
src/test/java/com/m3pro/groundflip/service/AuthServiceTest.java
src/test/java/com/m3pro/groundflip/service/UserServiceTest.java
src/test/resources/application-test.yml

- 애플로 회원가입 시 리프레시 토큰을 받도록 함
- 애플 계정의 회원탈퇴시 애플과 연결된 토큰을 만료시키는 기능 구현
- 애플의 서버에서 자원을 가져올 필요가 없었기에 애플의 access token과 refresh token 을 발급 받지 않았었다.
- 하지만 애플 에서 애플 로그인을 한경우 회원탈퇴시 애플과 연결을 끊어주어야한다.
- 끊으려면 token 이 필요하다. 그렇기 때문에 애플 로그인시 토큰을 발급 받는 로직을 추가했고 RDB에 저장하였다.
- 회원 탈퇴시 RDB에 저장되어있던 토큰을 활용하여 연결을 끊어준다.
- 기존에는 access token 하나만 받았지만 애플은 authorization code 를 받았어야 했기에 인터페이스를 맞출수가 없었다.
- 일부 인터페이스는 유지 했지만 authService의 login 메서드는 분리되게 되었다.

M3-230 애플 계정 탈퇴 기능 구현

---

.github/workflows/ci.yml
build.gradle
src/main/java/com/m3pro/groundflip/config/RedisConfig.java
src/main/java/com/m3pro/groundflip/controller/PixelController.java
src/main/java/com/m3pro/groundflip/exception/ErrorCode.java
src/main/java/com/m3pro/groundflip/service/CommunityService.java
src/main/java/com/m3pro/groundflip/service/PixelService.java
src/main/java/com/m3pro/groundflip/service/StepService.java
src/main/java/com/m3pro/groundflip/util/DateUtils.java
src/test/java/com/m3pro/groundflip/service/CommunityServiceTest.java
src/test/java/com/m3pro/groundflip/service/PixelServiceTest.java
src/test/java/com/m3pro/groundflip/service/StepServiceTest.java
src/test/java/com/m3pro/groundflip/util/DateUtilsTest.java

- 랭킹 갱신 할 때 동시성 문제 해결
- 테스트 커버리지 70%로 올림
동시에 같은 유저가 같은 픽셀을 여러번 요청하면 요청한 만큼 점수가 올라가는 문제
예를 들어 
{
"userId": 446,
"communityId": null,
"x": 1000,
"y": 1000
}
이런 요청을 동시에 10번 보내면 current_pixel_count 점수에 1만 추가 되어야하는데 4가 추가되는 문제 발생
동시에 DB 에서 pixel을 읽어오는데 바뀐게 반영되지 않은채로 읽어져서 여러 스레드에서 user_id 가 null 인 값으로 읽어와서 여러 스레드에서 redis 에 플러스 1 요청을 보내 생기는 문제이다.
- 스레드에서 락을 거는 것은 분산환경에서 동작하지 않으니 제외했다.
- DB에서 락을 거는 것은 DB에 부하가 전가된다고 생각되어 제외했다.
- 결국 레디스를 사용해서 분산락을 거는 방법으로 해결했다.
- Redisson 이라는 것을 사용하여 pub/sub 구조 락을 대기하는 방식으로 구현했다.

M3-253 픽셀 차지 할 때 따닥 수정

---

src/main/java/com/m3pro/groundflip/domain/entity/global/BaseTimeEntity.java
src/main/java/com/m3pro/groundflip/service/PixelService.java

- 픽셀의 소유주를 변경 할 때 동일한 소유주이면 수정날짜를 변경하도록 수정
옛날에 방문했던 픽셀을 이번주에 다시 방문하면 개인전 모드에서 내 땅으로 표시가 안되는 문제
최초 방문시에만 pixel 테이블의 user_id가 바뀌어 modified at 이 수정된다. 따라서 이미 user_id가 나인 상태에서 재방문하면 user_id 가 변경되지 않으므로 modified at이 변경되지 않는다.
따라서 이번주 차지 중인 픽셀을 검색할떄 modified at 이 옛날 날짜로 되어있어서 필터링이 안되서 생기는 문제이다.
이미 내가 차지한 픽셀이면 modified_at 을 현재 날짜로 변경한다.

M3-281 옛날에 차지 했던 픽셀이 주가 지나고 다시 파지하면 내 것으로 인식되지 않는 문제

---

src/main/java/com/m3pro/groundflip/controller/UserController.java
src/main/java/com/m3pro/groundflip/domain/dto/user/FcmTokenRequest.java
src/main/java/com/m3pro/groundflip/domain/entity/FcmToken.java
src/main/java/com/m3pro/groundflip/domain/entity/global/BaseTimeEntity.java
src/main/java/com/m3pro/groundflip/repository/FcmTokenRepository.java
src/main/java/com/m3pro/groundflip/service/FcmService.java
src/main/java/com/m3pro/groundflip/service/PixelService.java
src/main/java/com/m3pro/groundflip/service/RankingService.java
src/main/java/com/m3pro/groundflip/service/UserService.java
src/test/java/com/m3pro/groundflip/service/FcmServiceTest.java
src/test/java/com/m3pro/groundflip/service/RankingServiceTest.java
src/test/java/com/m3pro/groundflip/service/UserServiceTest.java

- fcm token 등록 api 구현
- 회원 탈퇴시 기존 등록 된 토큰도 삭제 하도록 구현
- fcm 공식 문서를 보면 권장사항 나와있다. 
- 서버에 등록 토큰을 저장합니다.
- 서버에 토큰 타임스탬프를 구현하고 토큰이 변경될때 타임스탬프를 정기적으로 업데이트
- 업데이트 된지 2달된 토큰은 비활성화된 유저일 확률이 크기에 삭제
- 정기적으로 토큰 업데이트
- 푸시 알림후 응답이 잘못되면 토큰 삭제
등이 권장사항으로 적혀있다. 
- 그래서 나는 FcmToken 테이블을 만들어서 user_id, token, modified_at 을 저장하게 했다.
- modified_at 이 타임스탬프이며 업데이트 가능하다.
- 앱이 켜질 때 마다토큰을 서버에 전송하게 했기에 정기적 토큰 업데이트도 만족한다.
- 업데이트 된지 2달된 토큰은 배치 서버에서 지우는 것이 적합하여 보여 작업하지 않았다.
- 푸시 알림 후 응답이 잘못된 경우는 아직 푸시 알림을 전송하는 코드가 없어서 구현하지 않았다.

M3-286 FCM 토큰 관리기능 서버 구현

---

.github/workflows/ci.yml
src/main/java/com/m3pro/groundflip/controller/RankingController.java
src/main/java/com/m3pro/groundflip/repository/PixelUserRepository.java
src/main/java/com/m3pro/groundflip/repository/RankingRedisRepository.java
src/main/java/com/m3pro/groundflip/service/PixelManager.java
src/main/java/com/m3pro/groundflip/service/PixelReader.java
src/main/java/com/m3pro/groundflip/service/RankingService.java
src/test/java/com/m3pro/groundflip/repository/RankingRedisRepositoryTest.java
src/test/java/com/m3pro/groundflip/service/PixelManagerTest.java
src/test/java/com/m3pro/groundflip/service/PixelReaderTest.java
src/test/java/com/m3pro/groundflip/service/RankingServiceTest.java

- redis 를 사용한 집계방식으로 변경
- DB 에 실시간으로 개수를 집계하는 것은 부하가 너무 많이 든다고 판단.
- Redis 에 미리 적용해두는 것으로 개선. 이미 방문했는지 찾는 작업은 큰 부하는 걸리지 않는다. 
- Redis Sorted set 에 저장 했기 떄문에 랭킹도 집계 가능하다.

M3-329 누적 픽셀 count 쿼리 최적화

---

src/main/java/com/m3pro/groundflip/controller/CommunityController.java
src/main/java/com/m3pro/groundflip/domain/dto/community/CommunityInfoResponse.java
src/main/java/com/m3pro/groundflip/domain/entity/Community.java
src/main/java/com/m3pro/groundflip/repository/UserCommunityRepository.java
src/main/java/com/m3pro/groundflip/service/CommunityService.java
src/test/java/com/m3pro/groundflip/service/CommunityServiceTest.java

- 그룹 정보 반환 API 구현
실제 기능 이름과 코드에서 적는 이름이 다르다. 실제는 그룹이지만 그룹기능을 위해 그룹 테이블을 만들지 못한다. 왜냐하면 group 이 mySQL 예약어라서 그렇다. 따라서 테이블 이름은 community 이다.
이러다 보니 api 이름은 group 인데 메서드 이름은 community 인 상황이 발생하여 혼란 스럽다. 때문에 용어를 community 로 통일 했다. 
위 두 정보는 매번 집계하기 쉽지 않는 값들이다. 때문에 비정규화 하여 컬럼에 추가하였다. occupyPixel 로직에서 업데이트 할 때 위 두 컬럼도 같이 업데이트 해주어여할 것이다.
그룹에 대한 랭킹이 아직 만들어지 않아 해당부분은 반환하도록 구현을 못했다. 때문에 그룹 구현하는 사람이 넣어주어야할듯하다.
```
public CommunityInfoResponse findCommunityById(Long communityId) {
Community community = communityRepository.findById(communityId)
.orElseThrow(() -> new AppException(ErrorCode.GROUP_NOT_FOUND));
Long memberCount = getMemberCount(community);
// ToDo : 랭킹 하시는 분이 구현하신 것 토대로 communityRanking, currentPixelCount, accumulatePixelCount만 채워주세요.
return CommunityInfoResponse.from(community, 0, …
```

M3-344 그룹 정보 반환 API 구현

---

src/main/java/com/m3pro/groundflip/controller/PixelController.java
src/main/java/com/m3pro/groundflip/domain/dto/pixel/CommunityPixelInfoResponse.java
src/main/java/com/m3pro/groundflip/domain/dto/pixel/PixelOwnerCommunityResponse.java
src/main/java/com/m3pro/groundflip/domain/dto/pixel/VisitedCommunityInfo.java
src/main/java/com/m3pro/groundflip/domain/dto/pixelUser/VisitedCommunity.java
src/main/java/com/m3pro/groundflip/repository/CommunityRankingRedisRepository.java
src/main/java/com/m3pro/groundflip/repository/PixelUserRepository.java
src/main/java/com/m3pro/groundflip/repository/RankingRedisRepository.java
src/main/java/com/m3pro/groundflip/repository/UserRankingRedisRepository.java
src/main/java/com/m3pro/groundflip/service/CommunityRankingService.java
src/main/java/com/m3pro/groundflip/service/PixelReader.java
src/main/java/com/m3pro/groundflip/service/UserRankingService.java
src/test/java/com/m3pro/groundflip/repository/RankingRedisRepositoryTest.java
src/test/java/com/m3pro/groundflip/repository/UserRankingRedisRepositoryTest.java
src/test/java/com/m3pro/groundflip/service/CommunityRankingServiceTest.java
src/test/java/com/m3pro/groundflip/service/UserRankingServiceTest.java

- 픽셀의 상세 정보를 반환하는 api 구현
RankingRedisRepository 를 리팩토링 했다. 기존에는 `UserRankingRedisRepository` 와 `CommunityRankingRedisRepository` 가 sorted set 의 키값만 다르고 완전히 동일한 코드를 사용하고 있어 코드가 너무 많이 중복되었다.
때문에 중복된 로직을 RankingRedisRepository 로 묶고 sorted set 의 키값을 생성자로 받아 각각의 도메인에 대해 다른 키값을 가지는 Repository 객체를 생성할 수 있게 리팩토링 했다.
```
public class RankingRedisRepository {
private static final int RANKING_START_INDEX = 0;
private static final int RANKING_END_INDEX = 29;
private final String currentPixelRankingKey;
private final String accumulatePixelRankingKey;
private final RedisTemplate<String, String> redisTemplate;
private ZSetOperations<String, String> zSetOperations;
public RankingRedisRepository(RedisTemplate<String, String> redisTemplate, String currentPixelRankingKey,
String accumulatePixelRankingKey) { …
```

M3-349 그룹전 픽셀 상세 정보 반환 api 구현

---

src/main/java/com/m3pro/groundflip/domain/entity/Pixel.java
src/main/java/com/m3pro/groundflip/service/PixelManager.java
src/test/java/com/m3pro/groundflip/repository/PixelRepositoryTest.java
src/test/java/com/m3pro/groundflip/repository/PixelUserRepositoryTest.java
src/test/java/com/m3pro/groundflip/service/PixelManagerTest.java

- pixel 테이블 새로 삽입
- 새로 발견했을시 삽입하는 로직 구현
```sql
CREATE TABLE pixel_non_null_user LIKE pixel;
INSERT INTO pixel_non_null_user
SELECT *
FROM pixel
WHERE user_id IS NOT NULL;
```
- pixel 테이블에 픽셀이 들어있는지 확인 후 없으면 만든다.
```java
Long pixel_id = x * 4156 + y + 1
```
```java
double currentLongitude = upper_left_lon + (y * lon_per_pixel);
double currentLatitude = upper_left_lat - (x * lat_per_pixel);
double currentLongitude = 125.905952 + (3514 * 0.000909);
double currentLatitude = 38.240675 - (3489 * 0.000724);
```

M3-378 pixel 테이블 최적화

---

src/main/java/com/m3pro/groundflip/controller/PixelController.java
src/main/java/com/m3pro/groundflip/domain/entity/DailyPixel.java
src/main/java/com/m3pro/groundflip/repository/DailyPixelRepository.java
src/main/java/com/m3pro/groundflip/service/PixelReader.java
src/test/java/com/m3pro/groundflip/service/UserServiceTest.java

- 사용자의 데일리  픽셀 API 구현 완료
- 네이티브 쿼리로 한번에 가져오는 것을 목표로 함.
- 기존의 걸음수 API와 같은 방식으로 동작하게 끔 함

백엔드 데일리 픽셀 api 구현

---

.github/workflows/cd_dev.yml
.github/workflows/cd_prod.yml
src/main/java/com/m3pro/groundflip/controller/PixelController.java
src/main/java/com/m3pro/groundflip/domain/dto/pixel/ClusteredPixelCount.java
src/main/java/com/m3pro/groundflip/domain/dto/pixel/RegionInfo.java
src/main/java/com/m3pro/groundflip/domain/dto/pixel/naverApi/ReverseGeocodingResult.java
src/main/java/com/m3pro/groundflip/domain/entity/CompetitionCount.java
src/main/java/com/m3pro/groundflip/domain/entity/Pixel.java
src/main/java/com/m3pro/groundflip/domain/entity/Region.java
src/main/java/com/m3pro/groundflip/domain/entity/UserRegionCount.java
src/main/java/com/m3pro/groundflip/enums/RegionLevel.java
src/main/java/com/m3pro/groundflip/repository/CompetitionCountRepository.java
src/main/java/com/m3pro/groundflip/repository/RegionRepository.java
src/main/java/com/m3pro/groundflip/repository/UserRegionCountRepository.java
src/main/java/com/m3pro/groundflip/service/PixelManager.java
src/main/java/com/m3pro/groundflip/service/RegionService.java
src/main/java/com/m3pro/groundflip/service/ReverseGeoCodingService.java
src/main/resources/application-dev.yml
src/main/resources/application-local.yml
src/main/resources/application-prod.yml
src/test/java/com/m3pro/groundflip/service/PixelManagerTest.java
src/test/java/com/m3pro/groundflip/service/UserServiceTest.java
src/test/resources/application-test.yml

- 완료한 사항1
- 완료한 사항2
- 무슨 이유로 어떻게 코드를 변경했는지
- 기술적 고민

M3-382 픽셀 클러스터링 집계

---

src/main/java/com/m3pro/groundflip/controller/AnnouncementController.java
src/main/java/com/m3pro/groundflip/domain/dto/announcement/AnnouncementInfoResponse.java
src/main/java/com/m3pro/groundflip/domain/dto/announcement/AnnouncementResponse.java
src/main/java/com/m3pro/groundflip/domain/dto/announcement/EventResponse.java
src/main/java/com/m3pro/groundflip/domain/entity/Announcement.java
src/main/java/com/m3pro/groundflip/domain/entity/Event.java
src/main/java/com/m3pro/groundflip/domain/entity/UserActivityLog.java
src/main/java/com/m3pro/groundflip/repository/AnnouncementRepository.java
src/main/java/com/m3pro/groundflip/repository/EventRepository.java
src/main/java/com/m3pro/groundflip/repository/UserActivityLogRepository.java
src/main/java/com/m3pro/groundflip/service/AnnouncementService.java
src/main/java/com/m3pro/groundflip/service/FcmService.java
src/test/java/com/m3pro/groundflip/service/FcmServiceTest.java

- event 테이블 생성
- event 테이블 반환 로직 구현
- announcement 테이블 생성
- 공지사항 목록 페이지네이션 적용
- 공지사항 상세보기 기능 구현
- 공지사항, 조회수 집계 기능 구현
- 후에 공지사항이 많아질 것 을 대비하여 커서기반 페이지네이션 적용
- 조회수 카운트를 집계하는 로직 구현
- dau 를 정확히 알기 위해 앱을 킨 사용자들의 로그를 수집하도록 했다.

M3-353 이벤트 데이터 응답하는 api 및 공지사항 api 구현

---

src/main/java/com/m3pro/groundflip/repository/AnnouncementRepository.java
src/main/java/com/m3pro/groundflip/service/PixelManager.java

- save 메소드를 saveAndFlush 로 수정
- 클러스터링 부분에서 에러가 발생
- user_region_count 와 competition_count 에서 같은 지역의 데이터가 두번 동시에 삽입되어 발생함
- `org.springframework.dao.IncorrectResultSizeDataAccessException: Query did not return a unique result: 2 results were returned`
- 코드에 분명 분산락을 적용해두었는데 왜 발생하는지 처음에 이해가 안되었는데 코드를 보니 알 수 있었다.
- 기존에 만들어둔 count 가 없을 때 count 데이터를 생성하는 로직에 `userRegionCountRepository.save(userRegionCount)`
- 이런 식으로 save 만 하였다. 트랜잭션 내에서 동작하기에 save 만 한다면 트랜잭션이 끝난후 커밋된다. 커밋되는 시간 까지 딜레이가 생기면 그 사이에 다른 트랜잭션이 반영되지 않는 데이터를 조회하여 하나 더 만들 수 있다.
- save 가 아닌 saveAndFlush 를 사용하여 트랜잭션 중에 커밋 하도록 한다.

M3-410 픽셀 차지시 클러스터링에서  동시성 문제

---

src/main/java/com/m3pro/groundflip/controller/PixelController.java
src/main/java/com/m3pro/groundflip/service/PixelManager.java
src/main/java/com/m3pro/groundflip/service/PixelManagerWithLock.java
src/test/java/com/m3pro/groundflip/service/AnnouncementServiceTest.java
src/test/java/com/m3pro/groundflip/service/PixelManagerTest.java
src/test/java/com/m3pro/groundflip/service/PixelReaderTest.java
src/test/java/com/m3pro/groundflip/service/RegionServiceTest.java

- 추가로 발생되는 동시성 문제를 해결
- 기존에는 락이 풀린 후에 트랜잭션이 반영되게 구현되어있었음
- 때문에 분산락을 제대로 사용하기 위해서는 락 안에서 강제 트랜잭션 커밋을 했어야하는데 이 것을 까먹고 제대로 적용하지 않아 문제 발생
- 또한 이벤트 기반으로 분리한 로직이 락안에서 사용하는 자원이라서 락이 제대로 적용되지 않는 문제가 발생하여 이벤트를 로직안으로 통합시켰다.

M3-412 동시성 문제 해결

---

src/main/java/com/m3pro/groundflip/domain/entity/Achievement.java
src/main/java/com/m3pro/groundflip/domain/entity/UserAchievement.java
src/main/java/com/m3pro/groundflip/enums/AchievementCategoryId.java
src/main/java/com/m3pro/groundflip/enums/SpecialAchievement.java
src/main/java/com/m3pro/groundflip/repository/AchievementRepository.java
src/main/java/com/m3pro/groundflip/repository/PixelUserRepository.java
src/main/java/com/m3pro/groundflip/repository/UserAchievementRepository.java
src/main/java/com/m3pro/groundflip/service/AchievementManager.java
src/main/java/com/m3pro/groundflip/service/CommunityService.java
src/main/java/com/m3pro/groundflip/service/PixelManager.java
src/test/java/com/m3pro/groundflip/service/CommunityServiceTest.java
src/test/java/com/m3pro/groundflip/service/PixelManagerTest.java

- 누적 업정 업데이트 기능 구현
- 일회성 업적 업데이트 기능 구현
- 땅의 주인이 바뀔 때, 새로운 땅을 방문 할 때, 하루에 처음 땅을 먹었을때를 관련 업적의 진행도를 업데이트 하게 구현했다.
- 각 업적 데이터에 다음 목표가 있는 경우, 업적의 id 가 기록되어있어 하나의 업적이 달성되면 다음 업적으로 넘어가도록 구현했다.

M3-415 업적 진행 기능 구현

---

src/main/java/com/m3pro/groundflip/service/PixelManagerWithLock.java

- 락이 해제 되지 않은 경우에만 락을 해제하는 로직 추가
부하 상황에서 땅을 차지 하는 로직에서 엄청나게 많은 에러 발생
스레드가 현재 소유하지 않은 락을 해제하려고 하면서 발생하는 문제 (추청)
```
} finally {
rLock.unlock();
}
```
기존 코드에서 무조건 락을 해제 하도록 구현

M3-412 스레드가 락을 소유하지 않았는데 락을 해제 하는 문제 해결

---

src/main/java/com/m3pro/groundflip/controller/RankingController.java
src/main/java/com/m3pro/groundflip/domain/entity/RankingHistory.java
src/main/java/com/m3pro/groundflip/repository/RankingHistoryRepository.java
src/main/java/com/m3pro/groundflip/repository/RankingRedisRepository.java
src/main/java/com/m3pro/groundflip/service/UserRankingService.java
src/main/java/com/m3pro/groundflip/util/DateUtils.java
src/test/java/com/m3pro/groundflip/service/UserRankingServiceTest.java

- 전체 유저에 대한 누적 랭킹을 반환하는 api 구현
- 특정 유저에 대한 누적 랭킹을 반환하는 api 구현
```
public static boolean isDateInCurrentWeek(LocalDate date) {
return getWeekOfDate(LocalDate.now()) == getWeekOfDate(date);
}
```
- 기존 코드에서는 단순 주차만 비교 하기 때문에 2024/01/01 과 2025/01/01 이 같은 주차로 판단되는 문제가 있었다.
- 따라서 기존의 주차 뿐만 아닌 년도도 같이 비교하도록 코드를 수정 하였다.
- 하지만 기본적인 년도로 비교 하게 되면 2024/12/31 과 2025/01/01 이 다른 주차로 판단되는 경우가 생겨 `weekBasedYear` 라는 것을 사용하여 비교 하였다.

M3-421 현재 누적 랭킹을 반환하는 api 구현
